spring.datasoure.url: jdbc:h2:file:./booking.db
security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 94a662c70a114fbc0a073a98c0883d14
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me